excluded_patterns = [
    # 🔞 Porn / Adult Content
    r"(?i)(?<!\w)anal[\W_]*(sex|fuck|porn|vids|pics|penetration|gape|toys)(?!\w)",
    r"(?i)\b(p[\W_]*o[\W_]*r[\W_]*n|x[\W_]*x[\W_]*x|only[\W_]*fans|cam[\W_]*girl|red[\W_]*tube|xhamster|xvideos|pornhub|brazzers|hentai|blow[\W_]*job|cuckold|incest|furry[\W_]*porn|taboo[\W_]*sex|barely[\W_]*legal|nude[\W_]*celebrities|sex[\W_]*tapes|adult[\W_]*content|escort[\W_]*service|call[\W_]*girls|happy[\W_]*ending|massage[\W_]*parlor|onlyfans)\b",
    r"(?i)\b(slutty|cumshot|gangbang|bukkake|creampie|deepthroat|masturbation|dildo|fleshlight|bdsm|bondage|fetish|kink|swingers|orgy|threesome|bareback|amateur[\W_]*porn|milf[\W_]*porn|teen[\W_]*sex)\b",
    
    # 💊 Spam / SEO / Scam
    r"(?i)\b(viagra|cialis|weight[\W_]*loss[\W_]*pills|male[\W_]*enhancement|miracle[\W_]*cure|free[\W_]*bitcoins|get[\W_]*rich[\W_]*quick|click[\W_]*here|buy[\W_]*now|subscribe[\W_]*for[\W_]*free|limited[\W_]*time[\W_]*offer|download[\W_]*this[\W_]*app|work[\W_]*from[\W_]*home|make[\W_]*money[\W_]*online|earn[\W_]*\$\d+[\W_]*per[\W_]*day|online[\W_]*casino|betting[\W_]*tips)\b",
    r"(?i)(?<!\w)(cheap|discount|best|top)[\W_]*(pills|meds|medication|pharmacy|drugs|rx)(?!\w)",
    r"(?i)\b(seo[\W_]*services|backlink[\W_]*packages|guest[\W_]*post[\W_]*service|increase[\W_]*your[\W_]*rankings|boost[\W_]*website[\W_]*traffic|improve[\W_]*search[\W_]*rankings)\b",
    
    # 🕷️ Malware / Hacking / Darknet
    r"(?i)\b(keygen|crack[\W_]*download|serial[\W_]*keys|warez|torrentz2|darknet[\W_]*market|sell[\W_]*cvv|carding[\W_]*forum|how[\W_]*to[\W_]*hack|phishing|zero[\W_]*day|bypass[\W_]*captcha|cheat[\W_]*codes|ddos[\W_]*service|botnets[\W_]*for[\W_]*sale|exploit[\W_]*kits|ransomware[\W_]*as[\W_]*service|password[\W_]*cracker|keylogger[\W_]*software)\b",
    r"(?i)\b(buy[\W_]*fake[\W_]*id|fake[\W_]*passport|counterfeit[\W_]*money|stolen[\W_]*credit[\W_]*cards|free[\W_]*hacking[\W_]*tools|leak[\W_]*database|breach[\W_]*data|dump[\W_]*passwords)\b",
    r"(?i)\b(silk[\W_]*road|alphabay|empire[\W_]*market|dark[\W_]*web[\W_]*links|onion[\W_]*directory|tor[\W_]*hidden[\W_]*services|how[\W_]*to[\W_]*access[\W_]*darkweb|bitcoin[\W_]*laundry|crypto[\W_]*mixer)\b",
    
    # 🤖 Low-Quality AI/MT Generated / Junk
    r"(?i)\b(spintax|lorem[\W_]*ipsum|AI[\W_]*generated[\W_]*nonsense|machine[\W_]*translated[\W_]*poorly|unique[\W_]*quality[\W_]*content|we[\W_]*are[\W_]*best[\W_]*article[\W_]*site|AI[\W_]*writer|read[\W_]*more[\W_]*for[\W_]*information|content[\W_]*spinning|article[\W_]*rewriter|autogenerated[\W_]*text|scraper[\W_]*content|auto[\W_]*blogging)\b",
    r"(?i)(this[\W_]*article[\W_]*will[\W_]*discuss|in[\W_]*conclusion[\W_]*we[\W_]*have[\W_]*discussed|as[\W_]*we[\W_]*have[\W_]*seen[\W_]*above|in[\W_]*today's[\W_]*article[\W_]*we[\W_]*will[\W_]*explore)",
    r"(?i)(this[\W_]*post[\W_]*contains[\W_]*affiliate[\W_]*links|generated[\W_]*by[\W_]*our[\W_]*AI[\W_]*tool|written[\W_]*by[\W_]*content[\W_]*bot|auto[\W_]*published[\W_]*article)",
    
    # ☣️ Hate / Extremism / Conspiracy / Misinformation
    r"(?i)\b(white[\W_]*genocide|kill[\W_]*all[\W_]*(\w+)|jews[\W_]*control[\W_]*the[\W_]*world|flat[\W_]*earth[\W_]*truth|nazi|heil[\W_]*hitler|kkk|black[\W_]*crime[\W_]*stats|migrant[\W_]*invasion|satanic[\W_]*elites|anti[\W_]*vax[\W_]*propaganda|plandemic|vaccine[\W_]*chips|fake[\W_]*moon[\W_]*landing|illuminati[\W_]*confirmed|new[\W_]*world[\W_]*order|qanon|deep[\W_]*state[\W_]*conspiracy|crisis[\W_]*actors|false[\W_]*flag[\W_]*operation)\b",
    r"(?i)\b(race[\W_]*war|racial[\W_]*holy[\W_]*war|ethnic[\W_]*cleansing|racial[\W_]*slurs|antisemitic[\W_]*conspiracy|zionist[\W_]*occupation|jewish[\W_]*question|white[\W_]*power|white[\W_]*nationalism|incel[\W_]*ideology)\b",
    r"(?i)\b(great[\W_]*replacement|white[\W_]*extinction|cultural[\W_]*marxism|globalist[\W_]*agenda|lizard[\W_]*people|chemtrails|microchip[\W_]*vaccine|5g[\W_]*covid[\W_]*connection|controlled[\W_]*demolition|sandy[\W_]*hook[\W_]*hoax)\b",
    
    # 🗯️ Forum / Comment Section Memespeak
    r"(?i)\b(inb4|copypasta|le[\W_]*epic|soyjak|NPC[\W_]*meme|rage[\W_]*comic|this[\W_]*post[\W_]*gave[\W_]*me[\W_]*cancer|discord[\W_]*mod|reddit[\W_]*moment|based[\W_]*and[\W_]*redpilled|greentext|cringe[\W_]*compilation|normie|chad|virgin|wojak|feels[\W_]*bad[\W_]*man|pepe|doge|wojak|pogchamp|monka[\w]+|pepega|sadge|kappa)\b",
    r"(?i)\b(updoot|downvote|karmawhore|repost|shitpost|circlejerk|hivemind|echo[\W_]*chamber|tldr|eli5|sauce|mods[\W_]*are[\W_]*gay|delete[\W_]*this|underrated[\W_]*comment|edit:[\W_]*thanks[\W_]*for[\W_]*the[\W_]*gold|this[\W_]is[\W_]the[\W_]way)\b",
    
    # 🚨 Clickbait / Fake News / Trash
    r"(?i)\b(you[\W_]*won't[\W_]*believe|top[\W_]*10|shocking|mind[\W_]*blowing|celebrity[\W_]*scandal|breaking:|truth[\W_]*about[\W_]*covid|doctors[\W_]*hate[\W_]*this[\W_]*trick|what[\W_]*happens[\W_]*next[\W_]*will[\W_]*shock[\W_]*you|gone[\W_]*wrong|gone[\W_]*sexual|in[\W_]*the[\W_]*hood)\b",
    r"(?i)\b(what[\W_]*they[\W_]*don't[\W_]*want[\W_]*you[\W_]*to[\W_]*know|this[\W_]*simple[\W_]*trick|one[\W_]*weird[\W_]*trick|shocking[\W_]*truth[\W_]*revealed|click[\W_]*to[\W_]*find[\W_]*out|number[\W_]*\d+[\W_]*will[\W_]*surprise[\W_]*you|things[\W_]*they[\W_]*aren't[\W_]*telling[\W_]*you)\b",
    
    # 🧼 Bad Domains / TLDs
    r"\.(?i)(tk|ml|cf|ga|gq|xyz|pw|top|loan|stream|click|club|win|review|work|men|party|link|biz|bid|trade|date|webcam|racing|faith|cricket|science|icu|monster|fun|online|site|bar|uno)$",
    
    # 🪤 Garbage Dictionary / SEO Filler
    r"(?i)\b(definition[\W_]*of|meaning[\W_]*of|synonyms[\W_]*for|rhymes[\W_]*with|words[\W_]*that[\W_]*start[\W_]*with|what[\W_]*does[\W_]*.*[\W_]*mean|stop[\W_]*words[\W_]*list|1000[\W_]*most[\W_]*common[\W_]*words|word[\W_]*frequency[\W_]*list|words[\W_]*related[\W_]*to|examples[\W_]*of[\W_]*.*[\W_]*words|dictionary[\W_]*definition|antonyms[\W_]*of)\b",
    
    # 🧱 High Template:Content Pages
    r"(?i)\b(template[\W_]*by|powered[\W_]*by[\W_]*.*(CMS|wordpress|wix|squarespace|shopify)|hosted[\W_]*by[\W_]*.*|designed[\W_]*using|copyright[\W_]*20\d{2}|all[\W_]*rights[\W_]*reserved|terms[\W_]*of[\W_]*service|privacy[\W_]*policy|404[\W_]*not[\W_]*found|website[\W_]*under[\W_]*construction)\b",
    r"(?i)\b(comment[\W_]*section[\W_]*below|share[\W_]*this[\W_]*post|like[\W_]*and[\W_]*subscribe|follow[\W_]*us[\W_]*on[\W_]*social[\W_]*media|sign[\W_]*up[\W_]*for[\W_]*our[\W_]*newsletter|join[\W_]*our[\W_]*mailing[\W_]*list)\b",
    
    # 🤖 AI Artifacts / Model-Specific Contamination
    r"(?i)\b(chatgpt|openai|anthropic|claude|large[\W_]*language[\W_]*model|LLM|prompt[\W_]*injection|hallucination[\W_]*in[\W_]*LLMs|GPT-?\d{1,3}|language[\W_]*model[\W_]*training|transformer[\W_]*architecture|attention[\W_]*mechanism|RLHF|reinforcement[\W_]*learning[\W_]*from[\W_]*human[\W_]*feedback|fine[\W_]*tuning[\W_]*llm|llama[\W_]*model|mistral[\W_]*ai|gemini[\W_]*model|bard|tokens|tokenizer|temperature[\W_]*setting|zero[\W_]*shot|few[\W_]*shot|instruction[\W_]*tuning)\b",
    
    # ❓ AI-Generated FAQ Trash
    r"(?i)\b(FAQ[\W_]*content[\W_]*generated[\W_]*by[\W_]*AI|frequently[\W_]*asked[\W_]*questions[\W_]*about[\W_]*.*|what[\W_]*is[\W_]*.*[\W_]*used[\W_]*for|how[\W_]*does[\W_]*.*[\W_]*work|common[\W_]*questions[\W_]*about|everything[\W_]*you[\W_]*need[\W_]*to[\W_]*know[\W_]*about)\b",
    r"(?i)\b(top[\W_]*questions[\W_]*about|the[\W_]*ultimate[\W_]*guide[\W_]*to|comprehensive[\W_]*overview[\W_]*of|complete[\W_]*beginner's[\W_]*guide[\W_]*to|step[\W_]*by[\W_]*step[\W_]*guide[\W_]*for)\b",
    
    # Clickbait-specific patterns
    r"(?i)\b(can[\W_]*you[\W_]*believe|unbelievable|watch[\W_]*till[\W_]*end|they[\W_]*don't[\W_]*want[\W_]*you[\W_]*to[\W_]*know|things[\W_]*you[\W_]*never[\W_]*knew|this[\W_]*will[\W_]*change[\W_]*your[\W_]*life|must[\W_]*see[\W_]*before[\W_]*it's[\W_]*deleted|they[\W_]*tried[\W_]*to[\W_]*ban[\W_]*this|secret[\W_]*they[\W_]*don't[\W_]*tell[\W_]*you|life[\W_]*hack|mind[\W_]*blown)\b",
    
    # Content-Farmed Pages
    r"(?i)\b(this[\W_]*page[\W_]*contains[\W_]*information[\W_]*about|learn[\W_]*everything[\W_]*you[\W_]*need[\W_]*to[\W_]*know[\W_]*about|we[\W_]*have[\W_]*compiled[\W_]*everything[\W_]*about|your[\W_]*one[\W_]*stop[\W_]*resource[\W_]*for|all[\W_]*you[\W_]*need[\W_]*to[\W_]*know[\W_]*about)\b",
    
    # GPT Artifact Mentions
    r"(?i)\b(as[\W_]*an[\W_]*AI[\W_]*language[\W_]*model|according[\W_]*to[\W_]*chatgpt|i[\W_]*asked[\W_]*openai|i[\W_]*prompted[\W_]*claude|as[\W_]*an[\W_]*AI[\W_]*assistant|i[\W_]*cannot[\W_]*provide[\W_]*medical[\W_]*advice|i[\W_]*don't[\W_]*have[\W_]*personal[\W_]*opinions|i[\W_]*don't[\W_]*have[\W_]*access[\W_]*to[\W_]*real-time[\W_]*information|my[\W_]*knowledge[\W_]*cutoff[\W_]*is|i[\W_]*cannot[\W_]*browse[\W_]*the[\W_]*internet)\b",
    
    # Data scraping / content farms
    r"(?i)\b(generated[\W_]*from[\W_]*scraped[\W_]*content|auto[\W_]*generated[\W_]*page|content[\W_]*farm|keyword[\W_]*stuffing|duplicate[\W_]*content|scraped[\W_]*from|computer[\W_]*generated[\W_]*text|automatically[\W_]*generated[\W_]*summary|ai[\W_]*content[\W_]*detected)\b",
    
    # Low-quality product reviews
    r"(?i)\b(sponsored[\W_]*review|paid[\W_]*partnership|advertorial|affiliate[\W_]*commission|gifted[\W_]*product|honest[\W_]*review[\W_]*of[\W_]*product[\W_]*i[\W_]*got[\W_]*for[\W_]*free|unboxing|product[\W_]*review[\W_]*farm)\b",
    
    # Link farms / content mills
    r"(?i)\b(useful[\W_]*links|related[\W_]*resources|sponsored[\W_]*links|check[\W_]*out[\W_]*these[\W_]*sites|for[\W_]*more[\W_]*information[\W_]*visit|our[\W_]*partners|our[\W_]*sponsors|recommended[\W_]*sites|external[\W_]*resources)\b",
    
    # Repetitive low-quality blog content
    r"(?i)\b(lifestyle[\W_]*blog|fashion[\W_]*trends|beauty[\W_]*tips|home[\W_]*decor[\W_]*ideas|diy[\W_]*projects|travel[\W_]*destinations|healthy[\W_]*recipes|weight[\W_]*loss[\W_]*journey)\b",
]

# Additional patterns for filtering specific content types
specialized_filters = {
    # E-commerce product pages with minimal unique content
    "ecommerce_templates": [
        r"(?i)\b(add[\W_]*to[\W_]*cart|buy[\W_]*now|product[\W_]*description|customer[\W_]*reviews|related[\W_]*products|shipping[\W_]*information|return[\W_]*policy|payment[\W_]*methods)\b",
        r"(?i)\b(out[\W_]*of[\W_]*stock|in[\W_]*stock|limited[\W_]*quantity|sale[\W_]*ends|discount[\W_]*code|promo[\W_]*code|coupon|free[\W_]*shipping|order[\W_]*now)\b"
    ],
    
    # Auto-generated weather/stock/sports data pages
    "auto_data_pages": [
        r"(?i)\b(current[\W_]*temperature|forecast[\W_]*for|weather[\W_]*conditions|high[\W_]*of|low[\W_]*of|precipitation[\W_]*chance|humidity[\W_]*level|wind[\W_]*speed)\b",
        r"(?i)\b(stock[\W_]*price|market[\W_]*cap|trading[\W_]*volume|day[\W_]*range|52[\W_]*week[\W_]*high|52[\W_]*week[\W_]*low|dividend[\W_]*yield|p\/e[\W_]*ratio)\b",
        r"(?i)\b(sports[\W_]*score|final[\W_]*score|game[\W_]*stats|player[\W_]*stats|match[\W_]*summary|league[\W_]*standings|team[\W_]*record)\b"
    ],
    
    # Calendar/event listing pages
    "calendar_pages": [
        r"(?i)\b(upcoming[\W_]*events|event[\W_]*calendar|schedule[\W_]*of[\W_]*events|mark[\W_]*your[\W_]*calendar|save[\W_]*the[\W_]*date|event[\W_]*details|location[\W_]*map|register[\W_]*now)\b"
    ],
    
    # Job listings
    "job_listings": [
        r"(?i)\b(job[\W_]*description|responsibilities|qualifications|requirements|salary[\W_]*range|benefits[\W_]*package|to[\W_]*apply|submit[\W_]*your[\W_]*resume|apply[\W_]*now|job[\W_]*id)\b"
    ],
    
    # Academic paper templates or auto-generated abstracts
    "academic_templates": [
        r"(?i)\b(abstract|introduction|methodology|literature[\W_]*review|results[\W_]*and[\W_]*discussion|conclusion|references|keywords|doi|pmid|elsevier|springer|wiley|ieee|journal[\W_]*of)\b"
    ]
} 
  